/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package roman;

import java.util.List;

public class Main {

    public static void main(String[] args) {
        RomanToArabicConverter converter = new RomanToArabicConverter();
        String romanNumber = converter.convertArabicToRoman(12);
        System.out.println(romanNumber);
    }
}
